import React from 'react';

import { Footer } from '@/components/footer';
import { NavBar } from '@/components/nav-bar';
import { Head } from '@/components/seo';
import './privacy-policy.scss';

const ProfileSettingsRoute: React.FC = () => {
  return (
    <>
      <Head description={'Asakiri | Privacy Policy'}></Head>
      <NavBar />
      <div className="main">
        <div className="container">
          <h1>Privacy Policy</h1>

          <p>
            This Privacy Policy describes Our policies and procedures on the
            collection, use and disclosure of Your information when You use the
            Service and tells You about Your privacy rights and how the law
            protects You.
          </p>

          <p>
            We use Your Personal data to provide and improve the Service. By
            using the Service, You agree to the collection and use of
            information in accordance with this Privacy Policy.
          </p>

          <h2>Interpretation and Definition</h2>

          <h3>Interpretation</h3>
          <p>
            The words of which the initial letter is capitalized have meanings
            defined under the following conditions. The following definitions
            shall have the same meaning regardless of whether they appear in
            singular or in plural.
          </p>

          <h3>Definition</h3>
          <ul>
            <li>
              <strong>Account:</strong> means a unique account created for You
              to access our Service or parts of our Service.
            </li>
            <li>
              <strong>Affiliate:</strong> means an entity that controls, is
              controlled by or is under common control with a party, where
              "control" means ownership of 50% or more of the shares, equity
              interest or other securities entitled to vote for election of
              directors or other managing authority.
            </li>
            <li>
              <strong>Application:</strong> means the software program provided
              by the Company used by you on any electronic device named Asakiri.
            </li>
            <li>
              <strong>Company:</strong> refers to Asakiri Pvt Ltd.
            </li>
            <li>
              <strong>Country:</strong> refers to: India.
            </li>
            <li>
              <strong>Device:</strong> means any device that can access the
              Service such as a computer, a cellphone or a digital tablet.
            </li>
            <li>
              <strong>Personal Data:</strong> is any information that relates to
              an identified or identifiable individual.
            </li>
            <li>
              <strong>Service:</strong> refers to the Application.
            </li>
            <li>
              <strong>Service Provider:</strong> means any natural or legal
              person who processes the data on behalf of the Company.
            </li>
            <li>
              <strong>Usage Data:</strong> refers to data collected
              automatically, either generated by the use of the Service or from
              the Service infrastructure itself.
            </li>
            <li>
              <strong>You:</strong> means the individual accessing or using the
              Service, or the company, or other legal entity on behalf of which
              such individual is accessing or using the Service, as applicable.
            </li>
          </ul>

          <h2>Collecting and Using Your Personal Data</h2>

          <h3>Types of Data Collected</h3>

          <h4>Personal Data</h4>
          <p>
            While using Our Service, We may ask You to provide Us with certain
            personally identifiable information that can be used to contact or
            identify You. Personally identifiable information may include, but
            is not limited to:
          </p>
          <ul>
            <li>Email address</li>
            <li>Name</li>
            <li>Usage Data</li>
          </ul>

          <h4>Usage Data</h4>
          <p>
            Usage Data is collected automatically when using the Service. Usage
            Data may include information such as Your Device's Internet Protocol
            address (e.g. IP address), browser type, browser version, and other
            diagnostic data.
          </p>

          <h3>Use of Your Personal Data</h3>
          <p>
            The Company may use Personal Data for various purposes such as
            providing and maintaining our Service, managing Your Account,
            contacting You, and for business transfers among others.
          </p>

          <h2>Retention of Your Personal Data</h2>
          <p>
            The Company will retain Your Personal Data only for as long as is
            necessary for the purposes set out in this Privacy Policy.
          </p>

          <h2>Transfer of Your Personal Data</h2>
          <p>
            Your information may be transferred to — and maintained on —
            computers located outside of Your state, province, country or other
            governmental jurisdiction where data protection laws may differ than
            those from Your jurisdiction.
          </p>

          <h2>Your Rights Regarding Personal Data</h2>
          <p>
            You have the right to delete or request that we assist in deleting
            your Personal Data that we have collected about You.
          </p>

          <h2>Disclosure of Your Personal Data</h2>
          <p>
            If the Company is involved in a merger, acquisition or asset sale,
            Your Personal Data may be transferred. We will provide notice before
            Your Personal Data is transferred and becomes subject to a different
            Privacy Policy.
          </p>

          <h2>Security of Your Personal Data</h2>
          <p>
            The security of Your Personal Data is important to Us; however, no
            method of transmission over the Internet is 100% secure.
          </p>

          <h2>Changes to this Privacy Policy</h2>
          <p>
            We may update Our Privacy Policy from time to time. We will notify
            You of any changes by posting the new Privacy Policy on this page.
          </p>

          <h2>Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, you can contact
            us via email for data deletion requests at support@asakiri.com.
          </p>
        </div>
      </div>
      <Footer />
    </>
  );
};
export default ProfileSettingsRoute;
